# Sample ci file to copy to your project
image: salesforcedx-gitlab-ci:latest
stages:
  - test
variables:
  CI_PROJECT_DIR: /app
  CI_SFDX_USERNAME: XXX@XXX
  CI_SFDX_CONSUMER_KEY: XXXXXXXXXXXXXXXXXXXXXXXXX
test:
  stage: test
  script:
    - ci-test.sh
  coverage: '/^\w*\s*\w*\s*(\w*).*$/'
